default_stages: [commit]
default_language_version:
  python: python3.12

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks 
    rev: v5.0.0  # latest stable
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: detect-private-key
      - id: requirements-txt-fixer

  - repo: https://github.com/astral-sh/ruff-pre-commit 
    rev: v0.11.2  # updated to recent stable
    hooks:
      - id: ruff
        args: [--fix]  # fixes issues but allows commit if fixed
        types: [python]
      - id: ruff-format
        types: [python]

ci:
  autoupdate_schedule: weekly
  skip: []
  submodules: false
