default_language_version:
  python: python3.12

repos:
  # General code hygiene tools
  - repo: https://github.com/pre-commit/pre-commit-hooks 
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: detect-private-key
      - id: requirements-txt-fixer

  # Python linter and formatter
  - repo: https://github.com/astral-sh/ruff-pre-commit 
    rev: v0.11.2
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        language_version: python3.12
        types_or: [python, pyi]

      - id: ruff-format
        language_version: python3.12
        types_or: [python, pyi]

# CI settings for auto-updates
ci:
  autoupdate_schedule: weekly
  skip: []
  submodules: false
