name: Full Stack CI/CD

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Pre-commit and Tools
        run: |
          pip install --upgrade pip
          pip install black flake8 pylint pre-commit

      - name: Run Pre-commit Hooks
        uses: pre-commit/action@v4  # Use the latest version
        with:
          extra_args: --show-diff-on-failure

  angular_tests:
    needs: linter
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: yarn
      - run: yarn run eslint . --ext .js,.jsx,.ts,.tsx
      - run: yarn test

  django_tests:
    needs: linter
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - run: python manage.py test

  deploy_frontend:
    needs: angular_tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: cd frontend && yarn build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Sync Angular Build to S3
        run: |
          aws s3 sync frontend/dist s3://${{ secrets.S3_BUCKET_NAME }} --delete

  deploy_backend:
    needs: django_tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install EB CLI via pip
        run: |
          pip install awsebcli --upgrade
          eb --version

      - name: Deploy Django App to Elastic Beanstalk
        run: |
          cd backend
          eb init -p python-3.11 ${{ secrets.EB_APPLICATION_NAME }} --region ${{ secrets.AWS_REGION }}
          eb use ${{ secrets.EB_ENVIRONMENT_NAME }}
          eb deploy
